---
# This is the top-level playbook that defines our entire infrastructure.

- hosts: all
  user: deploy
  sudo: True
  gather_facts: True
  vars_files:
    - vars/defaults.yml
    - vars/disabled_extras.yml
    - vars/mail.yml
    - vars/user.yml

  roles:
    - common
    - mailserver
    - tarsnap
    # - mailpile # fix this
