- name: Install Postfix 9.1 and related packages
  apt: pkg={{ item }} state=installed
  with_items:
    - libsasl2-modules
    - postfix
    - postfix-pcre
    #- postfix-mysql
    - python-psycopg2
    - sasl2-bin

- name: Create database user for mail server
  mysql_user: >
    user={{ mail_db_username }} password={{ mail_db_password }}
    state=present priv="mailserver.*:ALL"
  when: mail_db == "mysql"
  notify: import sql postfix

- name: Create database for mail server
  mysql_db: name={{ mail_db_database }} state=present
  when: mail_db == "mysql"
  notify: import sql postfix

- name: Copy import.sql
  template: >
    src=mailserver.{{ mail_db }}.j2 dest=/etc/postfix/import.sql
    owner=root group=root mode=0600
  notify: import sql postfix

- name: Create postfix maps directory
  file: path=/etc/postfix/maps state=directory owner=root group=root
  when: mail_header_privacy

- name: Copy smtp_header_checks.pcre
  copy: src=etc_postfix_maps_smtp_header_checks.pcre dest=/etc/postfix/maps/smtp_header_checks.pcre owner=root group=root
  when: mail_header_privacy

- name: Copy main.cf
  template: src=etc_postfix_main.cf.j2 dest=/etc/postfix/main.cf owner=root group=root
  notify: restart postfix

- name: Copy master.cf
  copy: src=etc_postfix_master.cf dest=/etc/postfix/master.cf owner=root group=root
  notify: restart postfix

- name: Copy additional postfix configuration files
  template: src=etc_postfix_{{ item }}.j2 dest=/etc/postfix/{{ item }} owner=root group=root
  with_items:
    - "{{ mail_db }}-virtual-alias-maps.cf"
    - "{{ mail_db }}-virtual-mailbox-domains.cf"
    - "{{ mail_db }}-virtual-mailbox-maps.cf"
  notify: restart postfix

- name: Set firewall rules for postfix
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
    - smtp
    - ssmtp
