---
# Defines tasks applicable across all machines in the infrastructure.

- name: "Test we're on Debian Wheezy"
  pause: seconds=0
  failed_when: >
    ansible_distribution != "Debian" or ansible_distribution_release != "wheezy"

- name: Update apt cache
  apt: update_cache=yes

- name: Upgrade all safe packages
  apt: upgrade=safe

- name: Install necessities and nice-to-haves
  apt: pkg={{ item }} state=installed
  with_items:
    - apticron
    - build-essential
    - sqlite3
    - ssl-cert
    - sudo
    - update-notifier-common

- name: Install unattended upgrades (Debian/Ubuntu only)
  apt: pkg=unattended-upgrades state=installed

- name: Apticron email configuration
  template: src=apticron.conf.j2 dest=/etc/apticron/apticron.conf

#- include: mariadb.yml tags=mariadb
- include: fake_encfs.yml tags=fake_encfs # sets up /decrypted
- include: users.yml tags=users
- include: ssl.yml tags=ssl
- include: ufw.yml tags=ufw
- include: security.yml tags=security
