---
# Defines tasks applicable across all machines in the infrastructure.

- name: Add backports repository
  apt_repository: repo="deb http://http.debian.net/debian wheezy-backports main"

- name: Update apt cache
  apt: update_cache=yes

- name: Upgrade all safe packages
  apt: upgrade=safe

- name: Install necessities and nice-to-haves
  apt: pkg={{ item }} state=installed
  with_items:
    - apticron
    - build-essential
    - htop
    - iftop
    - iotop
    - mosh
    - sqlite3
    - sudo
    - update-notifier-common
    - zsh

- name: Install necessities and nice-to-haves (from backports)
  apt: pkg={{ item }} state=installed default_release=wheezy-backports
  with_items:
    - git
    - tmux

- name: Install unattended upgrades (Debian/Ubuntu only)
  apt: pkg=unattended-upgrades state=installed
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Apticron email configuration
  template: src=apticron.conf.j2 dest=/etc/apticron/apticron.conf

#- include: mariadb.yml tags=mariadb
- include: fake_encfs.yml tags=fake_encfs # sets up /decrypted
- include: users.yml tags=users
- include: ssl.yml tags=ssl
- include: ufw.yml tags=ufw
- include: security.yml tags=security
- include: ntp.yml tags=ntp
